FROM 	   dealii/base:gcc-serial

MAINTAINER luca.heltai@gmail.com

USER 	   root

# general environment for docker
ENV        DEBIAN_FRONTEND=noninteractive \
           SPACK_ROOT=/usr/local \
           FORCE_UNSAFE_CONFIGURE=1

# install minimal spack dependencies
RUN        apt-get update \
           && apt-get install -y --no-install-recommends \
              ca-certificates \
              curl \
              environment-modules \
	      python \
           && rm -rf /var/lib/apt/lists/*

ENV 	   DUMMY=1

# install spack
RUN        curl -s -L https://api.github.com/repos/spack/spack/tarball \
           | tar xzC $SPACK_ROOT --strip 1
RUN        echo ". $SPACK_ROOT/share/spack/setup-env.sh" \
           > /etc/profile.d/spack.sh

# Make sure only one compiler is available
RUN 	   spack compilers && spack compiler rm gcc@5.5.0

# Make sure extras are ok
ADD       extras/packages.yaml $SPACK_ROOT/etc/spack/packages.yaml

# install software
RUN 	   spack install --only=dependencies dealii@develop \
	   && spack clean -a

RUN 	   spack install ninja numdiff environment-modules \
	   && spack clean -a 

# Make sure modules are well built
ADD       extras/modules $SPACK_ROOT/etc/spack/modules.yaml

# switch to normal user
USER       $USER
