name: developer

on:
  push:
    branches:
      - "developer*"
  schedule:
    - cron: "0 */12 * * *"

permissions:
  contents: read
  packages: write

jobs:
  build-master-docker-ubuntu:
    # Build images for different ubuntu versions on different platforms

    if: (github.event_name == 'schedule' && github.repository == 'dealii/docker-files') || github.event_name != 'schedule'

    name: build master docker ${{ matrix.ubuntu_version }} ${{ matrix.architecture }}
    runs-on: ${{ matrix.runs-on }}

    strategy:
      fail-fast: false
      matrix:
        ubuntu_version: [jammy, noble]
        architecture: [amd64, arm64]
        include:
          - architecture: amd64
            runs-on: ubuntu-24.04
            flags: ""
          - architecture: arm64
            runs-on: ubuntu-24.04-arm
            flags: -mno-outline-atomics
          # Use all available processors to build.
          # Specify the number of jobs explicitly since the default '0'
          # causes the github workers to disconnect (potential crash).
          - n_jobs: 4

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image of master ${{ matrix.ubuntu_version }}-${{ matrix.architecture }}
        id: build
        uses: docker/build-push-action@v6
        with:
          context: ./developer/
          cache-from: type=registry,ref=dealii/dependencies:${{ matrix.ubuntu_version }}
          cache-to: type=inline
          build-args: |
            IMG=${{ matrix.ubuntu_version }}
            NJOBS=${{ matrix.n_jobs }}
            VER=master
            FLAGS=${{ matrix.flags }}
          platforms: linux/${{ matrix.architecture }}
          tags: |
            ghcr.io/dealii/dealii:master-${{ matrix.ubuntu_version }}-${{ matrix.architecture }}
            dealii/dealii:master-${{ matrix.ubuntu_version }}-${{ matrix.architecture }}
          push: true

  merge:
    # Merge all images for a specific ubuntu version

    if: (github.event_name == 'schedule' && github.repository == 'dealii/docker-files') || github.event_name != 'schedule'

    runs-on: ubuntu-24.04
    needs:
      - build-master-docker-ubuntu

    strategy:
      fail-fast: false
      matrix:
        docker:
          - ghcr.io/dealii/dealii
          - dealii/dealii
        ubuntu_version:
          - jammy
          - noble

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Merge images of ${{ matrix.docker }}:${{ matrix.ubuntu_version }}
        run: |
          docker buildx imagetools create \
             -t ${{ matrix.docker }}:master-${{ matrix.ubuntu_version }} \
             ${{ matrix.docker }}:master-${{ matrix.ubuntu_version }}-amd64 \
             ${{ matrix.docker }}:master-${{ matrix.ubuntu_version }}-arm64
